"use client";

import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Header from "@/components/header/header";
import { ReduxProvider } from "@/store/provider";
import "./globals.css";

const poppins = Poppins({
	weight: ["400", "500", "600", "700"],
	subsets: ["devanagari", "latin"],
	fallback: ["sans-serif"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={poppins.className}>
				<ReduxProvider>
					<Header />
					<main className="container">{children}</main>
				</ReduxProvider>
			</body>
		</html>
	);
}
